#!/usr/bin/env python3
"""Builds vectors/lombokicons-vectors-v1.json (GP-11).

Expected outputs come from an independent Python implementation of the rendering
template in SPEC_LombokIcons section 3, written from the SPEC and not from the
JavaScript code, plus hand-written cases for options, escaping and validation.
The JavaScript build must reproduce every case byte for byte.

After editing, run:

    python3 vectors/build_vectors.py
    sha256sum vectors/lombokicons-vectors-v1.json > vectors/SHA256SUMS

and update the hash in docs/SPEC_LombokIcons_v<version>.md.
"""
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
registry = json.loads((ROOT / "src" / "icons.json").read_text(encoding="utf-8"))
ICONS = registry["icons"]

RE_SIZE = re.compile(r"^(?:0|[0-9]+(?:\.[0-9]+)?(?:px|em|rem|%|vw|vh|vmin|vmax|pt|ch|ex))$")
RE_COLOR = re.compile(
    r"^(?:#[0-9a-fA-F]{3,8}|[a-zA-Z]{3,30}|(?:rgb|rgba|hsl|hsla|hwb|lab|lch|oklab|oklch|color)\([0-9a-zA-Z.,% /+-]{1,64}\)"
    r"|var\(--[a-zA-Z0-9_-]{1,64}\))$"
)
SVG_OPEN = ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" '
            'stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"')


def esc(s):
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;").replace("'", "&#39;")


def render(name, opts=None):
    """SPEC §3, implemented independently."""
    opts = opts or {}
    icon = ICONS.get(name)
    if icon is None:
        return ""
    mode = opts.get("mode") if opts.get("mode") in ("line", "bold", "duo") else "line"
    cls = opts.get("class")
    cls = " ".join(re.split(r"[ \t\n\f\r]+", cls.strip(" \t\n\f\r"))) if isinstance(cls, str) else ""
    styles = []
    if isinstance(opts.get("size"), str) and RE_SIZE.fullmatch(opts["size"]):
        styles.append("--lf-size:" + opts["size"])
    if isinstance(opts.get("color"), str) and RE_COLOR.fullmatch(opts["color"]):
        styles.append("--lf-color:" + opts["color"])
    title = opts.get("title") if isinstance(opts.get("title"), str) else ""
    out = '<span class="lf' + (" " + esc(cls) if cls else "") + '"'
    if styles:
        out += ' style="' + esc(";".join(styles)) + '"'
    out += ">" + SVG_OPEN
    out += (' role="img" aria-label="' + esc(title) + '">' + "<title>" + esc(title) + "</title>") if title else ' aria-hidden="true" focusable="false">'
    if mode == "duo" and icon["duo_accent"]:
        out += '<path d="' + icon["duo_accent"] + '" class="lf-accent" fill="currentColor" opacity="0.32" stroke="none"/>'
    out += '<path d="' + icon["line"] + '"/>'
    if mode == "bold" and icon["bold_accent"]:
        out += '<path d="' + icon["bold_accent"] + '" class="lf-bold-fill" fill="currentColor" stroke="none"/>'
    return out + "</svg></span>"


cases = []


def add(name, opts, expected, note=None):
    case = {"id": f"render-{len(cases) + 1:03d}", "fn": "renderIcon", "name": name}
    if opts:
        case["options"] = opts
    if note:
        case["note"] = note
    case["expected"] = expected
    cases.append(case)


# 1) every icon in every mode with default options (generated by the Python implementation)
for name in ICONS:
    for mode in ("line", "bold", "duo"):
        add(name, {"mode": mode}, render(name, {"mode": mode}))

# 2) hand-written option cases (expected strings typed out, checked against the Python implementation)
HOME = ICONS["home"]["line"]
X = ICONS["x"]["line"]
HAND = [
    ("home", None, '<span class="lf">' + SVG_OPEN + ' aria-hidden="true" focusable="false"><path d="' + HOME + '"/></svg></span>', "defaults"),
    ("does-not-exist", None, "", "unknown name"),
    ("__proto__", None, "", "prototype keys are not icons"),
    ("constructor", None, "", "prototype keys are not icons"),
    ("x", {"mode": "sparkle"}, '<span class="lf">' + SVG_OPEN + ' aria-hidden="true" focusable="false"><path d="' + X + '"/></svg></span>', "unknown mode falls back to line"),
    ("x", {"class": "lf-xl  lf-spin "}, '<span class="lf lf-xl lf-spin">' + SVG_OPEN + ' aria-hidden="true" focusable="false"><path d="' + X + '"/></svg></span>', "class whitespace collapsed"),
    ("x", {"class": '" onmouseover="alert(1)'}, '<span class="lf &quot; onmouseover=&quot;alert(1)">' + SVG_OPEN + ' aria-hidden="true" focusable="false"><path d="' + X + '"/></svg></span>', "class escaped"),
    ("x", {"class": "<b>&'"}, '<span class="lf &lt;b&gt;&amp;&#39;">' + SVG_OPEN + ' aria-hidden="true" focusable="false"><path d="' + X + '"/></svg></span>', "class escaped"),
    ("x", {"size": "2rem"}, '<span class="lf" style="--lf-size:2rem">' + SVG_OPEN + ' aria-hidden="true" focusable="false"><path d="' + X + '"/></svg></span>', None),
    ("x", {"size": "24px"}, '<span class="lf" style="--lf-size:24px">' + SVG_OPEN + ' aria-hidden="true" focusable="false"><path d="' + X + '"/></svg></span>', None),
    ("x", {"size": "1.5em"}, '<span class="lf" style="--lf-size:1.5em">' + SVG_OPEN + ' aria-hidden="true" focusable="false"><path d="' + X + '"/></svg></span>', None),
    ("x", {"size": "0"}, '<span class="lf" style="--lf-size:0">' + SVG_OPEN + ' aria-hidden="true" focusable="false"><path d="' + X + '"/></svg></span>', None),
    ("x", {"size": "24"}, '<span class="lf">' + SVG_OPEN + ' aria-hidden="true" focusable="false"><path d="' + X + '"/></svg></span>', "unitless size ignored"),
    ("x", {"size": "2rem;background:red"}, '<span class="lf">' + SVG_OPEN + ' aria-hidden="true" focusable="false"><path d="' + X + '"/></svg></span>', "CSS injection ignored"),
    ("x", {"size": "2rem\n"}, '<span class="lf">' + SVG_OPEN + ' aria-hidden="true" focusable="false"><path d="' + X + '"/></svg></span>', "trailing newline rejected"),
    ("x", {"size": "\uff12rem"}, '<span class="lf">' + SVG_OPEN + ' aria-hidden="true" focusable="false"><path d="' + X + '"/></svg></span>', "non-ASCII digit rejected"),
    ("x", {"color": "rgb(1\u00a02\u00a03)"}, '<span class="lf">' + SVG_OPEN + ' aria-hidden="true" focusable="false"><path d="' + X + '"/></svg></span>', "non-ASCII space rejected"),
    ("x", {"class": "a\u00a0b"}, '<span class="lf a\u00a0b">' + SVG_OPEN + ' aria-hidden="true" focusable="false"><path d="' + X + '"/></svg></span>', "only ASCII whitespace collapsed"),
    ("x", {"size": "-1px"}, '<span class="lf">' + SVG_OPEN + ' aria-hidden="true" focusable="false"><path d="' + X + '"/></svg></span>', "negative size ignored"),
    ("x", {"color": "#e53e3e"}, '<span class="lf" style="--lf-color:#e53e3e">' + SVG_OPEN + ' aria-hidden="true" focusable="false"><path d="' + X + '"/></svg></span>', None),
    ("x", {"color": "#abc"}, '<span class="lf" style="--lf-color:#abc">' + SVG_OPEN + ' aria-hidden="true" focusable="false"><path d="' + X + '"/></svg></span>', None),
    ("x", {"color": "teal"}, '<span class="lf" style="--lf-color:teal">' + SVG_OPEN + ' aria-hidden="true" focusable="false"><path d="' + X + '"/></svg></span>', None),
    ("x", {"color": "rgb(10 20 30 / 50%)"}, '<span class="lf" style="--lf-color:rgb(10 20 30 / 50%)">' + SVG_OPEN + ' aria-hidden="true" focusable="false"><path d="' + X + '"/></svg></span>', None),
    ("x", {"color": "oklch(0.7 0.1 200)"}, '<span class="lf" style="--lf-color:oklch(0.7 0.1 200)">' + SVG_OPEN + ' aria-hidden="true" focusable="false"><path d="' + X + '"/></svg></span>', None),
    ("x", {"color": "var(--brand-500)"}, '<span class="lf" style="--lf-color:var(--brand-500)">' + SVG_OPEN + ' aria-hidden="true" focusable="false"><path d="' + X + '"/></svg></span>', None),
    ("x", {"color": "red;background:url(x)"}, '<span class="lf">' + SVG_OPEN + ' aria-hidden="true" focusable="false"><path d="' + X + '"/></svg></span>', "CSS injection ignored"),
    ("x", {"color": 'red" onclick="x'}, '<span class="lf">' + SVG_OPEN + ' aria-hidden="true" focusable="false"><path d="' + X + '"/></svg></span>', "attribute injection ignored"),
    ("x", {"color": "url(javascript:x)"}, '<span class="lf">' + SVG_OPEN + ' aria-hidden="true" focusable="false"><path d="' + X + '"/></svg></span>', "url() not allowed"),
    ("x", {"color": "expression(alert(1))"}, '<span class="lf">' + SVG_OPEN + ' aria-hidden="true" focusable="false"><path d="' + X + '"/></svg></span>', "unknown function not allowed"),
    ("x", {"size": "2rem", "color": "#000"}, '<span class="lf" style="--lf-size:2rem;--lf-color:#000">' + SVG_OPEN + ' aria-hidden="true" focusable="false"><path d="' + X + '"/></svg></span>', "size before color"),
    ("x", {"title": "Tutup"}, '<span class="lf">' + SVG_OPEN + ' role="img" aria-label="Tutup"><title>Tutup</title><path d="' + X + '"/></svg></span>', "accessible name"),
    ("x", {"title": 'Close "dialog" <now>'}, '<span class="lf">' + SVG_OPEN + ' role="img" aria-label="Close &quot;dialog&quot; &lt;now&gt;"><title>Close &quot;dialog&quot; &lt;now&gt;</title><path d="' + X + '"/></svg></span>', "title escaped"),
    ("x", {"title": ""}, '<span class="lf">' + SVG_OPEN + ' aria-hidden="true" focusable="false"><path d="' + X + '"/></svg></span>', "empty title is decorative"),
    ("home", {"mode": "duo", "class": "lf-lg", "size": "3rem", "color": "#123456", "title": "Beranda"},
     '<span class="lf lf-lg" style="--lf-size:3rem;--lf-color:#123456">' + SVG_OPEN + ' role="img" aria-label="Beranda"><title>Beranda</title>'
     '<path d="' + ICONS["home"]["duo_accent"] + '" class="lf-accent" fill="currentColor" opacity="0.32" stroke="none"/><path d="' + HOME + '"/></svg></span>',
     "all options"),
]
for name, opts, expected, note in HAND:
    independent = render(name, opts)
    assert independent == expected, f"hand-written case disagrees with SPEC implementation: {name} {opts}\n{independent}\n{expected}"
    add(name, opts, expected, note)

doc = {
    "name": "lombokicons-vectors",
    "version": 1,
    "spec": "docs/SPEC_LombokIcons (section 3)",
    "icons_sha256_source": "src/icons.json",
    "functions": {"renderIcon": "renderIcon(case.name, case.options) -> string"},
    "cases": cases,
}
out = pathlib.Path(__file__).with_name("lombokicons-vectors-v1.json")
out.write_text(json.dumps(doc, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
print(f"{len(cases)} cases -> {out}")
